[package]
name = "xacross"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
itertools = "0.14.0"
owo-colors = "4.1.0"
strum = { version = "0.27.0", features = ["derive"] }
